import type { Metadata } from "next";
 import "./globals.scss";

 
export const metadata: Metadata = {
  title: "Next Pro Max Template",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    children
  );
}
